channels:
- conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.2
  - numpy<2
  - seaborn=0.13.2
  - scikit-learn=1.5.1
  - ipykernel=6.29.5
  - setuptools=74.1.2
  - ipywidgets=8.1.5
  - pytest=8.3.3
  - pyqt=5.15.11
  - xgboost=2.1.1
  - pip
  - pip:
      - ydata-profiling==4.9.0
      - category-encoders==2.6.3
      - feature-engine==1.8.1
      - dill==0.3.9
      - mlflow==2.16.2
      - optuna==4.0.0
      - virtualenv==20.26.6
name: loantap-credit-default-risk-model