[tool.poetry]
name = "loantap-credit-default-risk-model"
version = "0.1.0"
description = ""
authors = ["jyothisable <athuljyothis18@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
